fpostgres-peoplex:
        image: postgres:10-alpine
        restart: always
        ports:
          - '5432:5432'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'peoplex'
        volumes:
           - ./init.sql:/docker-entrypoint-initdb.d/init.sql
adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8081
        




